name: LastMines
version: '${version}'
main: ru.last.mines.LastMines
api-version: '1.21'

depend: [ LLib ]
softdepend: [ PlaceholderAPI, BMenu, WorldEdit, DecentHolograms, FancyHolograms ]

author: Last
website: https://laststudio.space

permissions:
  lastmines.admin:
    default: op