name: LastMines
version: '0.1'
main: ru.last.mines.LastMines
api-version: '1.16'

depend: [ BLib ]
softdepend: [ PlaceholderAPI, BMenu, WorldGuard, WorldEdit, DecentHolograms, FancyHolograms ]

author: Last
description: Плагин на автошахты с большой кастомизацией и гибкой настройкой на 1.16.5 - 26.1.2 версиях
website: https://laststudio.space

commands:
  lastmines:
    aliases: [lmines, lmine, lm]
    permission: lastmines.admin

permissions:
  lastmines.admin:
    default: op